name: Build and push multi-platform image

on:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'

jobs:
  build_push:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-24.04
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image for ${{ matrix.arch }}
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/${{ github.repository }}:${{ matrix.arch }}-${{ github.ref_name }}
          push: true

  merge:
    name: Create and push manifest list
    runs-on: ubuntu-latest
    needs: build_push
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Create manifest list and push
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          TAG="${{ github.ref_name }}"
          
          echo "Creating manifest list for ${IMAGE}:${TAG}"
          
          DIGEST_AMD64=$(docker buildx imagetools inspect ${IMAGE}:amd64-${TAG} --raw | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')
          DIGEST_ARM64=$(docker buildx imagetools inspect ${IMAGE}:arm64-${TAG} --raw | jq -r '.manifests[] | select(.platform.architecture=="arm64") | .digest')
          
          echo "amd64 digest: $DIGEST_AMD64"
          echo "arm64 digest: $DIGEST_ARM64"
          
          docker manifest create ${IMAGE}:${TAG} \
            ${IMAGE}@${DIGEST_AMD64} \
            ${IMAGE}@${DIGEST_ARM64}
          
          docker manifest annotate ${IMAGE}:${TAG} ${IMAGE}@${DIGEST_ARM64} --os linux --arch arm64 --variant v8
          docker manifest annotate ${IMAGE}:${TAG} ${IMAGE}@${DIGEST_AMD64} --os linux --arch amd64
          
          docker manifest push ${IMAGE}:${TAG}